//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont

import 'package:flutter/material.dart' show IconData;

class MyIcons2 {
  static const String _family = 'iconfont';
  
  MyIcons2._();
  
  static const IconData Icon_Renwu = IconData(0xe613, fontFamily: _family); 
  static const IconData Icon_Yonghu = IconData(0xe652, fontFamily: _family); 
  static const IconData Icon_Zhuye = IconData(0xe667, fontFamily: _family); 
}
