//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont

import 'package:flutter/material.dart' show IconData;

class TestIcons {
  static const String _family = 'my_test';

  TestIcons._();

  static const IconData Testfayinwang = IconData(0xe620, fontFamily: _family);
}
