///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Config {
/*
{
  "pubspecName": "pubspec.yaml.g",
  "readPath": "assets/fonts/",
  "writePath": "lib/icons/",
  "dirName": "",
  "css": ""
}
*/

  /// 保存pubspec的名字
  String pubspecName;

  /// iconfont 目录
  String readPath;

  /// 生成的icon 目录
  String writePath;

  /// 通过css 创建的文件夹名
  String dirName;

  /// css 网络地址
  String css;

  /// 1
  Config({
    this.pubspecName,
    this.readPath,
    this.writePath,
    this.dirName,
    this.css,
  });

  /// 1
  Config.fromJson(Map<String, dynamic> json) {
    pubspecName = json["pubspecName"]?.toString();
    readPath = json["readPath"]?.toString();
    writePath = json["writePath"]?.toString();
    dirName = json["dirName"]?.toString();
    css = json["css"]?.toString();
  }

  /// 1
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["pubspecName"] = pubspecName;
    data["readPath"] = readPath;
    data["writePath"] = writePath;
    data["dirName"] = dirName;
    data["css"] = css;
    return data;
  }
}
