//  This file is automatically generated. DO NOT EDIT, all your changes would be lost.
//  https://pub.dartlang.org/packages/iconfont

import 'package:flutter/material.dart' show IconData;

class MyIcons {
  static const String _family = 'myiconfont';
  static const String _package = 'myPackage';
  
  MyIcons._();
  
  static const IconData Myicon_Chushi = IconData(0xe64f, fontFamily: _family, fontPackage: _package); 
  static const IconData Myicon_Zhileng = IconData(0xe64b, fontFamily: _family, fontPackage: _package); 
  static const IconData Myicon_Zhire = IconData(0xe64c, fontFamily: _family, fontPackage: _package); 
  static const IconData Myicon_Zidong = IconData(0xe7ee, fontFamily: _family, fontPackage: _package); 
}
